name: strongR-frida

on:
  schedule:
    - cron: "0 9/12 * * *"
  workflow_dispatch:

jobs:
  check_version:
    runs-on: ubuntu-20.04


    steps:
      - name: test
        id: pullFridaLatestRelease
        uses: actions/github-script@v3.1.0

        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            core.setOutput('token', ${{secrets.GITHUB_TOKEN}});
